#!/bin/bash
# WARNING: this writes to the owner's running game. Only run it with the owner's OK (see docs/ENGINE_NOTES.md);
# the ZMCPDev exec file is shared with other sessions and a bad render hook breaks the game every frame.
# Prefer tests/luacheck.py + tests/sim/test_sim.py (offline).
# Build a single-player dev bundle of the whole mod (shared + server + client Lua) and hand it to the
# ZMCPDev exec watcher (dev/ZMCPDev must be in ~/Zomboid/mods and the game running):
#   dev/bundle_sp.sh            -> writes ~/Zomboid/Lua/zmcp_dev_exec.lua and waits for zmcp_dev_result.txt
#   dev/bundle_sp.sh extra.lua  -> same, with extra.lua appended (a test script that runs after the load)
# `require` lines for our own files are stripped because loadstring bundles cannot require each other.
set -e
DIR=$(cd "$(dirname "$0")/.." && pwd)
LUA="$DIR/mod/Contents/mods/ZomboidMCP/42/media/lua"
OUT=~/Zomboid/Lua/zmcp_dev_exec.lua
RES=~/Zomboid/Lua/zmcp_dev_result.txt
seen=""
{
  echo "-- generated by dev/bundle_sp.sh $(date +%T)"
  for f in "$LUA/shared/ZomboidMCP/Json.lua" \
           "$LUA/shared/ZomboidMCP/CollisionSprites.lua" \
           "$LUA/server/ZomboidMCP/Bridge.lua" \
           "$LUA/server/ZomboidMCP/Api/Common.lua" \
           "$LUA/server/ZomboidMCP/Api/"*.lua \
           "$LUA/client/ZomboidMCP/ClientBase64.lua" \
           "$LUA/client/ZomboidMCP/ClientTextures.lua" \
           "$LUA/client/ZomboidMCP/ClientSprites.lua" \
           "$LUA/client/ZomboidMCP/ClientFalling.lua" \
           "$LUA/client/ZomboidMCP/ClientOverlay.lua" \
           "$LUA/client/ZomboidMCP/ClientInput.lua" \
           "$LUA/client/ZomboidMCP/ClientModels.lua" \
           "$LUA/client/ZomboidMCP/Client.lua"; do
    case " $seen " in *" $f "*) continue ;; esac; seen="$seen $f"
    echo "do -- $(basename "$f")"
    grep -v '^require "ZomboidMCP/' "$f" | sed 's/^return .*$/-- (bundle: top-level return removed)/'
    echo "end"
  done
  echo "ZMCPClient.hello()"
  if [ -n "$1" ]; then echo "do -- $1"; cat "$1"; echo "end"; fi
  echo 'return "bundle loaded"'
} > "$OUT.tmp"
before=$(cat "$RES" 2>/dev/null || true)
mv "$OUT.tmp" "$OUT"
for i in $(seq 1 40); do
  sleep 0.25
  now=$(cat "$RES" 2>/dev/null || true)
  if [ "$now" != "$before" ] && [ -n "$now" ]; then echo "$now"; exit 0; fi
done
echo "no result after 10 s (is the game running and unpaused?)"; exit 1
